[mgr]
prepend_keymap = [
  { on = "<Enter>", run  = "plugin smart-enter", desc = "Enter the child directory, or open the file"},

  { on = "q", run = "close", desc = "Close the current tab, or quit if it's last" },

  { on = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files" },

  { on = ["e", "c"], run = [ "shell 'code $@' --block" ], desc = "Edit using VSCode" },
  { on = ["e", "z"], run = [ "shell 'zed $@' --block" ], desc = "Edit using Zed" },
  { on = ["e", "m"], run = [ "shell 'micro $@' --block" ], desc = "Edit using micro" },
  { on = ["e", "h"], run = [ "shell 'hx $@' --block" ], desc = "Edit using helix" },
]
