[font]
size = 18.0

[font.normal]
family = "Cascadia Code NF"

[colors.normal]
black = "0x010000"
blue = "0x032cbf"
cyan = "0x58c3c6"
green = "0x59bd38"
magenta = "0xba43c1"
red = "0xb9301c"
white = "0xe5e5e5"
yellow = "0xc7c43f"

[colors.bright]
black = "0x696868"
blue = "0x6875f6"
cyan = "0x8efbfd"
green = "0x8df579"
magenta = "0xed81f8"
red = "0xed766d"
white = "0xffffff"
yellow = "0xfffb7f"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"
